ignore:
  - "packages/**/src/defaults.ts"
  - "packages/**/src/index.ts"
  - "packages/**/src/plugin.ts"
  - "packages/core-error-tracker-bugsnag/**/*"
  - "packages/core-error-tracker-sentry/**/*"
  - "packages/core-graphql/**/*"
  - "packages/core-http-utils/**/*"
  - "packages/core-logger-winston/src/formatter.ts"
  - "packages/core-snapshots-cli/**/*"
  - "packages/core-tester-cli/**/*"
  - "packages/core-webhooks/src/database/migrations/**/*"
  - "packages/core/**/*"
