version: '2'

services:
  db:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: "ark-cored2"
        MYSQL_USER: "ark"
        MYSQL_PASSWORD: "ark"
        MYSQL_ROOT_PASSWORD: "ark"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
 