export const between = (actual, expected): boolean => actual > expected.min && actual < expected.max;
export const contains = (actual, expected): boolean => actual.includes(expected);
export const eq = (actual, expected): boolean => actual === expected;
export const falsy = (actual): boolean => actual === false;
export const gt = (actual, expected): boolean => actual > expected;
export const gte = (actual, expected): boolean => actual >= expected;
export const lt = (actual, expected): boolean => actual < expected;
export const lte = (actual, expected): boolean => actual <= expected;
export const ne = (actual, expected): boolean => actual !== expected;
export const notBetween = (actual, expected): boolean => !between(actual, expected);
export const regexp = (actual, expected): boolean => new RegExp(expected).test(actual);
export const truthy = (actual): boolean => actual === true;
