export const between = (actual, expected) => actual > expected.min && actual < expected.max;
export const contains = (actual, expected) => actual.includes(expected);
export const eq = (actual, expected) => actual === expected;
export const falsy = actual => actual === false;
export const gt = (actual, expected) => actual > expected;
export const gte = (actual, expected) => actual >= expected;
export const lt = (actual, expected) => actual < expected;
export const lte = (actual, expected) => actual <= expected;
export const ne = (actual, expected) => actual !== expected;
export const notBetween = (actual, expected) => !between(actual, expected);
export const regexp = (actual, expected) => new RegExp(expected).test(actual);
export const truthy = actual => actual === true;
