export const Identifiers: Record<string, symbol> = {
    // Application
    Application: Symbol.for("Application<Instance>"),
    ApplicationDirPrefix: Symbol.for("Application<DirPrefix>"),
    ApplicationEnvironment: Symbol.for("Application<Environment>"),
    ApplicationNamespace: Symbol.for("Application<Namespace>"),
    ApplicationNetwork: Symbol.for("Application<Network>"),
    ApplicationToken: Symbol.for("Application<Token>"),
    ApplicationVersion: Symbol.for("Application<Version>"),
    // Crypto
    Crypto: Symbol.for("Crypto<NetworkConfig>"),
    // Managers
    CacheManager: Symbol.for("Manager<Cache>"),
    ConfigManager: Symbol.for("Manager<Config>"),
    DatabaseManager: Symbol.for("Manager<Database>"),
    FilesystemManager: Symbol.for("Manager<Filesystem>"),
    LogManager: Symbol.for("Manager<Log>"),
    QueueManager: Symbol.for("Manager<Queue>"),
    ValidationManager: Symbol.for("Manager<Validation>"),
    // Services
    ActionService: Symbol.for("Service<Actions>"),
    CacheService: Symbol.for("Service<Cache>"),
    ConfigService: Symbol.for("Service<Config>"),
    EventDispatcherService: Symbol.for("Service<EventDispatcher>"),
    FilesystemService: Symbol.for("Service<Filesystem>"),
    LogService: Symbol.for("Service<Log>"),
    QueueService: Symbol.for("Service<Queue>"),
    ScheduleService: Symbol.for("Service<Schedule>"),
    ValidationService: Symbol.for("Service<Validation>"),
    DatabaseService: Symbol.for("Service<Database>"),
    BlockchainService: Symbol.for("Service<Blockchain>"),
    P2PService: Symbol.for("Service<P2P>"),
    SnapshotService: Symbol.for("Service<Snapshot>"),
    StateService: Symbol.for("Service<State>"),
    TransactionPoolService: Symbol.for("Service<TransactionPool>"),
    // Repositories
    ConfigRepository: Symbol.for("Repository<Config>"),
    ServiceProviderRepository: Symbol.for("Repository<ServiceProvider>"),
};
