Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.provision :shell, path: "../../bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.synced_folder "../../../", "/vagrant"
end
