import "./delegate-registration";
import "./delegate-resignation";
import "./ipfs";
import "./multi-payment";
import "./multi-signature";
import "./second-signature";
import "./timelock-transfer";
import "./transfer";
import "./vote";
