/**
 * Data we will use for filling the database before performing test queries.
 * Each property is used for both single and plural queries, considering
 * the `blocks` query returns `[Block]`, whereas `block` returns `Block.`
 */
module.exports = {
  blocks: [
    {
      id: '777',
      version: 0,
      timestamp: 100,
      previousBlock: 'undef',
      height: 1,
      numberOfTransactions: 1,
      totalAmount: 7.0,
      totalFee: 0.0,
      reward: 2.0,
      payloadLength: 208080,
      payloadHash: 'JOIAASLKUUOIAS',
      generatorPublicKey: '03178cf6623c326fe9352264a01b42cc5dddbff2688a446a63b8a8987021c',
      blockSignature: 'ASFASFQWEFASFSDGASFASD',
      transactions: [],
      generator: {}
    },
    {
      id: '123',
      version: 0,
      timestamp: 200,
      previousBlock: '777',
      height: 2,
      numberOfTransactions: 1,
      totalAmount: 7.0,
      totalFee: 0.0,
      reward: 2.0,
      payloadLength: 208080,
      payloadHash: 'ASDASDAASLKKUJOIAS',
      generatorPublicKey: 'arbitrary',
      blockSignature: 'KLJKLJHUUIODGASFASD',
      transactions: [],
      generator: {}
    },
    {
      id: '7',
      version: 0,
      timestamp: 300,
      previousBlock: '123',
      height: 3,
      numberOfTransactions: 1,
      totalAmount: 7.0,
      totalFee: 0.0,
      reward: 2.0,
      payloadLength: 208080,
      payloadHash: 'LKJHLAKSUIO',
      generatorPublicKey: 'another public key',
      blockSignature: 'AXXCVMJNMKLJXN',
      transactions: [],
      generator: {}
    }
  ],
  transactions: [
    {
      id: 'test tx 1',
      version: 0,
      timestamp: 50,
      senderPublicKey: '03178cf6623c326fe9352264a01b42cc5dddbff2688a446a63b8a8987021c07ff6',
      recipientId: 'play music',
      type: 0,
      vendorField: 'FFSDFGSDGEWSDGSDG',
      amount: 7,
      fee: 0,
      signature: 'ASDASDFGSDGSDFASD',
      block: 777,
      recipient: {},
      sender: {}
    },
    {
      id: 'test tx 2',
      version: 0,
      timestamp: 150,
      senderPublicKey: 'the public key',
      recipientId: 'somewhere safe',
      type: 0,
      vendorField: 'KLJKLJKLAJSKLJ',
      amount: 7,
      fee: 0,
      signature: 'LJKLUIOUIOUIO',
      block: 123,
      recipient: {},
      sender: {}
    },
    {
      id: 'test tx 3',
      version: 0,
      timestamp: 250,
      senderPublicKey: 'another public key',
      recipientId: '0xb',
      type: 0,
      vendorField: 'KLJHKLHIOUIU',
      amount: 7,
      fee: 0,
      signature: 'SDFLJKLJSDF',
      block: 7,
      recipient: {},
      sender: {}
    }
  ],
  wallets: [
    {
      address: 'AdXpdaTXD9s2Nw23Sys7Crbinvsj6ohUA6',
      publicKey: '03178cf6623c326fe9352264a01b42cc5dddbff2688a446a63b8a8987021c07ff6',
      secondPublicKey: null,
      balance: 8,
      vote: null,
      voted: false,
      username: 'jeremiG',
      lastBlock: 777,
      votebalance: 8,
      multisignature: null,
      dirty: false,
      producedBlocks: 1,
      missedBlocks: 0,
      forgedFees: 0,
      forgedRewards: 0,
      transactions: [],
      blocks: []
    },
    {
      address: 'play music',
      publicKey: 'a public key',
      secondPublicKey: null,
      balance: 8,
      vote: null,
      voted: false,
      username: 'sunnyB',
      lastBlock: 123,
      votebalance: 8,
      multisignature: null,
      dirty: false,
      producedBlocks: 1,
      missedBlocks: 0,
      forgedFees: 0,
      forgedRewards: 0,
      transactions: [],
      blocks: []
    },
    {
      address: 'somewhere safe',
      publicKey: 'another public key',
      secondPublicKey: null,
      balance: 8,
      vote: null,
      voted: false,
      username: 'cheesePuff',
      lastBlock: 7,
      votebalance: 8,
      multisignature: null,
      dirty: false,
      producedBlocks: 1,
      missedBlocks: 0,
      forgedFees: 0,
      forgedRewards: 0,
      transactions: [],
      blocks: []
    }
  ]
}
