// TODO put together similar matchers (for example all 'types' matchers)
// so that we can require() a collection of coherent matchers

require('./fields/address')
require('./fields/public-key')
require('./api/transaction')
require('./api/response')
require('./api/peer')
require('./api/block')
require('./models/delegate')
require('./models/transaction')
require('./models/wallet')
require('./transactions/valid')
require('./transactions/valid-second-signature')
require('./transactions/types/delegate-resignation')
require('./transactions/types/delegate')
require('./transactions/types/ipfs')
require('./transactions/types/multi-payment')
require('./transactions/types/multi-signature')
require('./transactions/types/second-signature')
require('./transactions/types/timelock-transfer')
require('./transactions/types/transfer')
require('./transactions/types/vote')
require('./blockchain/dispatch')
require('./blockchain/execute-on-entry')
require('./blockchain/transition')
