name: Functional

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    basic:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:10.8
                env:
                    POSTGRES_USER: ark
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: ark_unitnet
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Update system
              run: sudo apt-get update -y
            - name: Install xsel & postgresql-client
              run: sudo apt-get install -q xsel postgresql-client
            - name: Install and build packages
              run: yarn setup
            - name: Create .core/database directory
              run: mkdir -p $HOME/.core/database
            - name: Delegate Registration
              run: yarn test __tests__/functional/transaction-forging/delegate-registration.test.ts
            - name: Second Signature Registration
              run: yarn test __tests__/functional/transaction-forging/second-signature-registration.test.ts
            - name: Transfer
              run: yarn test __tests__/functional/transaction-forging/transfer.test.ts
            - name: Vote
              run: yarn test __tests__/functional/transaction-forging/vote.test.ts
              env:
                  CORE_DB_DATABASE: ark_unitnet
                  CORE_DB_USERNAME: ark
                  POSTGRES_USER: ark
                  POSTGRES_PASSWORD: password
                  POSTGRES_DB: ark_unitnet

    aip11:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:10.8
                env:
                    POSTGRES_USER: ark
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: ark_unitnet
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Update system
              run: sudo apt-get update -y
            - name: Install xsel & postgresql-client
              run: sudo apt-get install -q xsel postgresql-client
            - name: Install and build packages
              run: yarn setup
            - name: Create .core/database directory
              run: mkdir -p $HOME/.core/database
            - name: Delegate Resignation
              run: yarn test __tests__/functional/transaction-forging/delegate-resignation.test.ts
            - name: HTLC Claim
              run: yarn test __tests__/functional/transaction-forging/htlc-claim.test.ts
            - name: HTLC Lock
              run: yarn test __tests__/functional/transaction-forging/htlc-lock.test.ts
            - name: HTLC Refund
              run: yarn test __tests__/functional/transaction-forging/htlc-refund.test.ts
            - name: IPFS
              run: yarn test __tests__/functional/transaction-forging/ipfs.test.ts
            - name: Multi Payment
              run: yarn test __tests__/functional/transaction-forging/multi-payment.test.ts
            - name: Multi Signature Registration
              run: yarn test __tests__/functional/transaction-forging/multi-signature-registration.test.ts
              env:
                  CORE_DB_DATABASE: ark_unitnet
                  CORE_DB_USERNAME: ark
                  POSTGRES_USER: ark
                  POSTGRES_PASSWORD: password
                  POSTGRES_DB: ark_unitnet

    magistrate:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:10.8
                env:
                    POSTGRES_USER: ark
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: ark_unitnet
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Update system
              run: sudo apt-get update -y
            - name: Install xsel & postgresql-client
              run: sudo apt-get install -q xsel postgresql-client
            - name: Install and build packages
              run: yarn setup
            - name: Create .core/database directory
              run: mkdir -p $HOME/.core/database
            - name: Bridgechain Registration
              run: yarn test __tests__/functional/transaction-forging/bridgechain-registration.test.ts
            - name: Bridgechain Resignation
              run: yarn test __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
            - name: Bridgechain Update
              run: yarn test __tests__/functional/transaction-forging/bridgechain-update.test.ts
            - name: Business Registration
              run: yarn test __tests__/functional/transaction-forging/business-registration.test.ts
            - name: Business Resignation
              run: yarn test __tests__/functional/transaction-forging/business-resignation.test.ts
            - name: Business Update
              run: yarn test __tests__/functional/transaction-forging/business-update.test.ts
              env:
                  CORE_DB_DATABASE: ark_unitnet
                  CORE_DB_USERNAME: ark
                  POSTGRES_USER: ark
                  POSTGRES_PASSWORD: password
                  POSTGRES_DB: ark_unitnet
