name: Mainnet sync

on:
    schedule:
        - cron: '0 10 * * *'

jobs:
    mainnet-sync:
        runs-on: ubuntu-latest

        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SYNC_HOST }}
                username: ${{ secrets.SYNC_USERNAME }}
                password: ${{ secrets.SYNC_PASSWORD }}
                port: ${{ secrets.SYNC_PORT }}
                script_stop: true
                script: bash mainnet-sync-result.sh